In [4]:
import pandas as pd

In [5]:
data = pd.read_csv("/Users/AndreaLopera/Desktop/product-incident-dashboard/data/bosch-production-line-performance/train_date.csv")

In [6]:
data.head()

,Id,L0_S0_D1,L0_S0_D3,L0_S0_D5,L0_S0_D7,L0_S0_D9,L0_S0_D11,L0_S0_D13,L0_S0_D15,L0_S0_D17,...,L3_S50_D4246,L3_S50_D4248,L3_S50_D4250,L3_S50_D4252,L3_S50_D4254,L3_S51_D4255,L3_S51_D4257,L3_S51_D4259,L3_S51_D4261,L3_S51_D4263
0,4,82.24,82.24,82.24,82.24,82.24,82.24,82.24,82.24,82.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,1618.70,1618.70,1618.70,1618.70,1618.70,1618.70,1618.70,1618.70,1618.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,1149.20,1149.20,1149.20,1149.20,1149.20,1149.20,1149.20,1149.20,1149.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,602.64,602.64,602.64,602.64,602.64,602.64,602.64,602.64,602.64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1183747 entries, 0 to 1183746
Columns: 1157 entries, Id to L3_S51_D4263
dtypes: float64(1156), int64(1)
memory usage: 10.2 GB

In [10]:
data.isnull().count()

Id              1183747
L0_S0_D1        1183747
L0_S0_D3        1183747
L0_S0_D5        1183747
L0_S0_D7        1183747
                 ...
L3_S51_D4255    1183747
L3_S51_D4257    1183747
L3_S51_D4259    1183747
L3_S51_D4261    1183747
L3_S51_D4263    1183747
Length: 1157, dtype: int64

In [9]:
data.describe()

,Id,L0_S0_D1,L0_S0_D3,L0_S0_D5,L0_S0_D7,L0_S0_D9,L0_S0_D11,L0_S0_D13,L0_S0_D15,L0_S0_D17,...,L3_S50_D4246,L3_S50_D4248,L3_S50_D4250,L3_S50_D4252,L3_S50_D4254,L3_S51_D4255,L3_S51_D4257,L3_S51_D4259,L3_S51_D4261,L3_S51_D4263
count,1.183747e+06,673862.000000,673862.000000,673862.000000,673862.000000,673862.000000,673862.000000,673862.000000,673862.000000,673862.000000,...,30359.000000,30359.000000,30359.000000,30359.000000,30359.000000,59853.000000,59853.000000,59853.000000,59853.000000,59853.000000
mean,1.184050e+06,882.229068,882.229068,882.229068,882.229068,882.229068,882.229068,882.229068,882.229068,882.229068,...,1018.782158,1018.782158,1018.782158,1018.782158,1018.782158,1023.106448,1023.106448,1023.106448,1023.106448,1023.106448
std,6.834348e+05,506.724916,506.724916,506.724916,506.724916,506.724916,506.724916,506.724916,506.724916,506.724916,...,433.760618,433.760618,433.760618,433.760618,433.760618,433.928147,433.928147,433.928147,433.928147,433.928147
min,4.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.680000,0.680000,0.680000,0.680000,0.680000,0.680000,0.680000,0.680000,0.680000,0.680000
25%,5.921385e+05,392.800000,392.800000,392.800000,392.800000,392.800000,392.800000,392.800000,392.800000,392.800000,...,560.830000,560.830000,560.830000,560.830000,560.830000,561.000000,561.000000,561.000000,561.000000,561.000000
50%,1.184628e+06,909.230000,909.230000,909.230000,909.230000,909.230000,909.230000,909.230000,909.230000,909.230000,...,1225.430000,1225.430000,1225.430000,1225.430000,1225.430000,1291.210000,1291.210000,1291.210000,1291.210000,1291.210000
75%,1.775674e+06,1374.450000,1374.450000,1374.450000,1374.450000,1374.450000,1374.450000,1374.450000,1374.450000,1374.450000,...,1397.490000,1397.490000,1397.490000,1397.490000,1397.490000,1398.710000,1398.710000,1398.710000,1398.710000,1398.710000
max,2.367495e+06,1713.710000,1713.710000,1713.710000,1713.710000,1713.710000,1713.710000,1713.710000,1713.710000,1713.710000,...,1457.510000,1457.510000,1457.510000,1457.510000,1457.510000,1457.510000,1457.510000,1457.510000,1457.510000,1457.510000

In [11]:
data2 = pd.read_csv("/Users/AndreaLopera/Desktop/product-incident-dashboard/data/bosch-production-line-performance/train_numeric.csv")

In [12]:
data2.head()

,Id,L0_S0_F0,L0_S0_F2,L0_S0_F4,L0_S0_F6,L0_S0_F8,L0_S0_F10,L0_S0_F12,L0_S0_F14,L0_S0_F16,...,L3_S50_F4245,L3_S50_F4247,L3_S50_F4249,L3_S50_F4251,L3_S50_F4253,L3_S51_F4256,L3_S51_F4258,L3_S51_F4260,L3_S51_F4262,Response
0,4,0.030,-0.034,-0.197,-0.179,0.118,0.116,-0.015,-0.032,0.020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,7,0.088,0.086,0.003,-0.052,0.161,0.025,-0.015,-0.072,-0.225,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,9,-0.036,-0.064,0.294,0.330,0.074,0.161,0.022,0.128,-0.026,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,11,-0.055,-0.086,0.294,0.330,0.118,0.025,0.030,0.168,-0.169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [13]:
data2.isnull().count()

Id              1183747
L0_S0_F0        1183747
L0_S0_F2        1183747
L0_S0_F4        1183747
L0_S0_F6        1183747
                 ...
L3_S51_F4256    1183747
L3_S51_F4258    1183747
L3_S51_F4260    1183747
L3_S51_F4262    1183747
Response        1183747
Length: 970, dtype: int64